#!/usr/bin/env python
import os
import sys
from os.path import isfile, join, dirname, abspath, relpath
from pathlib import Path
import click
import subprocess
import csv
import subprocess

from ngs_utils.call_process import run_simple
from ngs_utils.file_utils import verify_file, safe_mkdir, verify_dir
from ngs_utils import logger
from ngs_utils.logger import warn, info
from ngs_utils.utils import set_locale; set_locale()
from ngs_utils import snakemake_utils
from nag import package_path


@click.command()
@click.argument('dna_bcbio', type=click.Path(exists=True))
@click.argument('dna_sample')
@click.argument('target_rule', nargs=-1)
@click.option('-o', 'output_dir', type=click.Path(), help='Output directory (default is "umccrise")')
@click.option('-s', '--sample')
@click.option('-R', '--rna-bcbio', type=click.Path())
@click.option('-r', '--rna-sample')
@click.option('--ensembl-release')
@click.option('--min-tvaf', help='Miniaml AF of tumor mutations (both in DNA and RNA). Default is 10 (%). '
                                 'Set if you know sample tumor purity.')

@click.option('-j', '--jobs', 'jobs', default=1, help='Maximum number of cores to use at single time (works both for '
              'local and cluster runs)')
@click.option('-c', '--cluster-auto', 'cluster', is_flag=True, help='Submit jobs to cluster')
@click.option('--unlock', is_flag=True, help='Propagaded to snakemake')
@click.option('--restart-times', default=1, help='Propagaded to snakemake.')

def main(dna_bcbio, dna_sample, target_rule=list(), sample=None, output_dir=None, rna_bcbio=None, rna_sample=None,
         ensembl_release=None, min_tvaf=None, jobs=None, cluster=False, unlock=False, restart_times=None,
    ):
    target_rule = list(target_rule)

    output_dir = output_dir or 'neoantigens'
    output_dir = safe_mkdir(abspath(output_dir))
    log_dir = safe_mkdir(join(output_dir, 'log'))
    logger.init(log_fpath_=join(log_dir, 'neoantigens.log'), save_previous=True)

    conf = dict()
    conf['dna_bcbio'] = verify_dir(dna_bcbio, is_critical=True)
    conf['dna_sample'] = dna_sample
    if rna_sample and rna_bcbio:
        conf['rna_sample'] = rna_sample
        conf['rna_bcbio'] = rna_bcbio
    else:
        if 'pvacfuse' in target_rule:
            logger.critical('Cannot run pVACfuse without RNA data')
        target_rule = ['pvacseq']
    if sample:
        conf['sample'] = sample
    if ensembl_release:
        conf['ensembl_release'] = ensembl_release
    if min_tvaf:
        conf['min_tvaf'] = min_tvaf

    #########################
    #### Setting cluster ####
    #########################

    cluster_log_dir = ''
    cluster_param = ''
    if cluster:
        cluster_log_dir = safe_mkdir(join(log_dir, 'cluster'))
        cluster_param = snakemake_utils.make_cluster_cmdl(cluster_log_dir, 'neoantigens')

    ###############################
    #### Building command line ####
    ###############################

    snakefile = join(package_path(), 'Snakefile')
    cmd = (
        f'snakemake '
        f'{" ".join(target_rule)} '
        f'--snakefile {snakefile} '
        f'--printshellcmds '
        f'--directory {output_dir} '
        f'-j {jobs} '
        f'--rerun-incomplete ' 
        f'--restart-times {restart_times} '
        f'{cluster_param} '
        f'--config {" ".join(k + "=" + v for k, v in conf.items())} '
    )

    #################
    #### Running ####
    #################

    def _append_sm_log():
        """ Snamemake writes its logs into a file like .snakemake/log/2018-09-16T113043.208368.snakemake.log
            We wanto to append its contents to our log file
        """
        sm_log_dir = join(output_dir, '.snakemake', 'log')
        sm_logs = sorted(Path(sm_log_dir).iterdir(), key=lambda fp: fp.stat().st_mtime)
        if sm_logs:
            with open(sm_logs[-1]) as fh:
                logger._write_to_file(fh.read())
                logger.info(f'Written snakemake log {sm_logs[0]} to {logger.log_fpath}')

    if unlock:
        logger.info('* Unlocking previous run... *')
        run_simple(cmd + ' --unlock')
        logger.info('* Now rerunning *')

    try:
        run_simple(cmd)

    except subprocess.CalledProcessError:
        _append_sm_log()
        logger.error('-' * 60)
        logger.error(f'Error running NAG: snakemake returned a non-zero status. Working directory: {output_dir}')
        if cluster_log_dir:
            logger.error(f'Review cluster job logs in {cluster_log_dir}')

    else:
        _append_sm_log()
        logger.info('-' * 60)
        logger.info(f'Finished.')
        logger.info(f'-' * 60)
        logger.info()

        sample = sample or dna_sample
        mut_calls_mhc1 = join(output_dir, f'pvacseq_results/MHC_Class_I/{sample}.final.tsv')
        mut_calls_mhc2 = join(output_dir, f'pvacseq_results/MHC_Class_II/{sample}.final.tsv')
        fus_calls_mhc1 = join(output_dir, f'pvacfuse_results/MHC_Class_I/{sample}.final.tsv')
        fus_calls_mhc2 = join(output_dir, f'pvacfuse_results/MHC_Class_II/{sample}.final.tsv')

        if not target_rule or 'pvacseq' in target_rule or 'all' in target_rule:
            _report(mut_calls_mhc1, 'SNPs and indels, MHC Class I',  join(output_dir, 'snps_and_indels_mhcI.tsv'))
            _report(mut_calls_mhc2, 'SNPs and indels, MHC Class II', join(output_dir, 'snps_and_indels_mhcII.tsv'))
        if not target_rule or 'pvacfuse' in target_rule or 'all' in target_rule:
            _report(fus_calls_mhc1, 'Fusions, MHC Class I',  join(output_dir, 'fusions_mhcI.tsv'))
            _report(fus_calls_mhc2, 'Fusions, MHC Class II', join(output_dir, 'fusions_mhcII.tsv'))
    finally:
        # adding read permissions to cluster logs
        subprocess.call(f'chmod -R a+r {log_dir}', shell=True)


def _pvac_seq_tsv_stats(fpath):
    total_lines = 0
    epitopes = set()
    muts = set()
    genes = set()
    hlas = set()

    with open(fpath) as fh:
        fieldnames = next(fh).strip().split('\t')
        csv_reader = csv.DictReader(fh, delimiter='\t', fieldnames=fieldnames)
        for entry in csv_reader:
            total_lines += 1
            muts.add((entry['Chromosome'], entry['Start'], entry['Stop']))
            epitopes.add(entry['MT Epitope Seq'])
            genes.add(entry['Gene Name'])
            hlas.add(entry['HLA Allele'])

    return total_lines, len(epitopes), len(muts), len(genes), len(hlas)


def _report(fpath, kind, final_link_path):
    if not verify_file(fpath, silent=True):
        logger.info(f'{kind}: no neoantigens called.')
        return

    if os.path.islink(final_link_path):
        os.unlink(final_link_path)
    os.symlink(relpath(fpath, dirname(final_link_path)), final_link_path)

    unfiltered_fpath = fpath.replace('.final.tsv', '.filtered.binding.tsv')
    if not isfile(unfiltered_fpath):
        unfiltered_fpath = fpath.replace('.final.tsv', '.filtered.coverage.tsv')

    lines,   epitopes,   muts,   genes,   hlas   = _pvac_seq_tsv_stats(fpath)
    u_lines, u_epitopes, u_muts, u_genes, u_hlas = _pvac_seq_tsv_stats(unfiltered_fpath)

    logger.info(f'{kind}:')
    logger.info(f'  - {epitopes} ({u_epitopes} unfiltered) epitopes from {muts} ({u_muts}) variants in '
                f'{genes} ({u_genes}) genes in context of {hlas} ({u_hlas}) HLA alleles.')
    logger.info(f'  - file: {fpath}')


if __name__ == '__main__':
    main()
